### ISSUE TITLE
SDX 0.7.1 - Localization.txt is looked for, even if not present - Unhandled Exception

### ISSUE THREAD

**Issue by SphereII** [7D2DSDX/SDX#2]
When SDX Launcher is copying files over into the Target, if the localization file isn't found, there's an unhandled exception.

This was discovered when met with a malformed localization file, and I tried to remove it from the BackUp so it doesn't get compiled.

**Comment by HAL-NINE-THOUSAND** [comment]
Should be sorted in 0.7.2

**Comment by SphereII** [comment]
Displays warning about missing file, and continues.
