### ISSUE TITLE
SDX 0.7: Feature Request: Allow sorting on Enabled

### ISSUE THREAD

**Issue by SphereII** [7D2DSDX/SDX#6]
Allow re-sorting of the SDX Launcher based on the Enabled status.

Optionally, allow sorting of build trigger order by the user, so they can specify the order of the build, in case of future dependency order.

**Comment by HAL-NINE-THOUSAND** [comment]
Should be sorted in 0.7.2

**Comment by SphereII** [comment]
Confirmed, thanks!
