### ISSUE TITLE
SDX 0.7: Set "Could not find node at XPath" as being a warning instead of fatal error

### ISSUE THREAD

**Issue by SphereII** [7D2DSDX/SDX#7]
`ERROR: Could not find node at XPath: /xui/ruleset[@name='default']/window_group[@name='toolbelt']/window[@name='HUDLeftStatBars']
`

Perhaps setting this type of error as a warning, rather than fatal error. As mods change, that option may no longer matter.
Since we are trying to remove that node, in that example, the SDX Parser didn't find it, so it shouldn't complain about it.

**Comment by HAL-NINE-THOUSAND** [comment]
I'd rather leave errors in. You may be trying to remove in this example but others would fail silently. SISO

**Comment by SphereII** [comment]
Should note that attempting to set a value that doesn't exist fails silently.

`SetWithXPath: /items/item/property[@class='Action0']/property[@name='Magazine_items'][@value='ironCrossbowBolt, steelCrossbowBolt, explodingCrossbowBolt, shotgunSlug']/@value
 Found 0
`
