### ISSUE TITLE
SDX 0.7.x: Check if feasible to skip re-instrumentation when a modified DLL is available

### ISSUE THREAD

**Issue by SphereII** [7D2DSDX/SDX#8]
It'd be nice if we could skip the re-instrumentation of the DLL, and allow the merging of XMLs to continue, if an Assembly-CSharp.dll already has the SDX hooks.

Currently, SDX Launcher will exit if it detects instrumentation, and won't continue to merge XML.

**Comment by XythQ** [comment]
This request is important for large mods like Starvation, where you need to patch the xml almost daily, but rebuilding the entire sdx mod is painful and complex, and is done infrequently.  This would allow a series of xml patches to be loaded between major releases without having to do manual edits to xml which get lost in the next major build.  Extra flag for patchscripts and scripts would be "nice to have", but xml is most critical.

**Comment by HAL-NINE-THOUSAND** [comment]
Should be sorted in 0.7.2 but may need additional tweaks
